name: Build and test

on:
  push:
    branches: main

  pull_request:
    branches: main

  workflow_dispatch:

env:
  RUST_VERSION: "1.68"

jobs:
  format-and-test:
    name: format-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy
      
      - name: Format
        run: |
          cargo fmt -- --color=always --check

      - name: Clippy
        run: |
          cargo clippy --tests
      
      - name: Install Wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      
      - name: Install cargo concordium
        run: |
          cargo install --locked cargo-concordium --version 3.0.0

      - name: Test
        run: cargo concordium test --out concordium-out/module.wasm.v1

